# Settings for "Read the Docs" build.
# See <https://docs.readthedocs.io/>.
version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.12"

mkdocs:
  configuration: mkdocs.yaml

python:
  install:
    - requirements: docs/requirements.txt
